---
# tasks file for prometheus-node-exporter
- name: create group prometheus
  group:
    name: prometheus
    state: present
- name: create user prometheus under prometheus group
  user:
    name: prometheus
    group: prometheus
    shell: /sbin/nologin
    state: present
- name: create required directories for prometheus node exporter
  file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    state: directory
  loop: "{{ prometheus_node_exporter_directories }}"
- name: check prometheus node exporter already exists
  stat:
    path: /usr/local/bin/node_exporter
  register: node_exporter_stat
- name: download and unarchive prometheus node exporter installation files
  unarchive:
    src: "{{ prometheus_node_exporter_installation_package_url }}"
    dest: /tmp/prometheus
    remote_src: true
  when: not node_exporter_stat.stat.exists
- name: copy prometheus node exporter executables to /usr/local/bin
  copy:
    src: "/tmp/prometheus/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64/node_exporter"
    dest: /usr/local/bin
    owner: prometheus
    group: prometheus
    mode: 0775
    remote_src: true
  when: not node_exporter_stat.stat.exists
- name: setup prometheus node exporter service
  copy:
    src: prometheus-node-exporter.service
    dest: /etc/systemd/system/prometheus-node-exporter.service
    owner: prometheus
    group: prometheus
    mode: 0775
- name: start and enable prometheus node exporter
  service:
    name: prometheus-node-exporter
    state: started
    enabled: true
    daemon_reload: true
- name: enable port 9100 for prometheus node exporter
  ansible.posix.firewalld:
    port: 9100/tcp
    state: enabled
    permanent: true
    immediate: true
  when: firewalld_enabled
- name: cleanup /tmp/prometheus
  file:
    path: /tmp/prometheus
    state: absent
